#!/bin/sh

# Runs the dev servers in tmux's vertical panes.
# It sets the working dir because our `make` scripts use relative paths

if [ `uname` = "Darwin" ]; then
  StartDB="./make startdb;"
fi

tmux new-session -s myproject -d # Detached session
tmux split-window -v # Second vertical pane
tmux split-window -v # Third

tmux send-keys -t 0 "cd $REPO/ServerSide; $StartDB ./make dev" Enter # Targets the first pane
tmux send-keys -t 1 "cd $REPO/AppSPA; ./make dev" Enter
tmux send-keys -t 2 "cd $REPO/AccountSPA; ./make dev" Enter

tmux attach -t myproject
