#!/bin/sh

# Runs the dev servers in tmux vertical panes
# It sets the current working dir because the scripts have relative paths

if [ `uname` = "Darwin" ]; then
  StartDB="./make startdb;"
fi

tmux new-session -s uxtely -d # Detached session
tmux split-window -v # Second vertical pane
tmux split-window -v # Third

tmux send-keys -t 0 "cd $REPO/ServerSide; $StartDB ./make dev" Enter # Targets the first pane
tmux send-keys -t 1 "cd $REPO/AppSPA; ./make dev" Enter
tmux send-keys -t 2 "cd $REPO/AccountSPA; ./make dev" Enter

tmux attach -t uxtely
